### ISSUE TITLE
React

### ISSUE THREAD

**Issue by Manubi** [BioComputingUP/feature-viewer-typescript#18]
Hi,
how can I use this package with react? :)
I've installed typescript, d3-axis, brush, scale, selection, shape and html-to-image. But it still doesn't show up in the div... Can someone just add a small prototype thanks! :)

**Comment by Lisanna** [comment]
Hi Manubi, thank you for your request! I have no experience with React, however I tested a simple example here: [repository](https://gitlab.com/lispal/gitlab-pages-react-example) - [published](https://lispal.gitlab.io/gitlab-pages-react-example/).
I hope this is enough of an example to solve you issue. I will take care of adding React documentation (and further testing) to the FV docs in the next days.

**Comment by Manubi** [comment]
Hi Lisanna,
Thanks for your help. The published version is working. But the repository I think is private. Can you make it public please. Thanks!

**Comment by Lisanna** [comment]
Yes, sorry! It should be public now ;)

**Comment by Lisanna** [comment]
I added very basic initialisation instructions to the docs (http://old.protein.bio.unipd.it/feature-viewer/), please re-open this issue if you encounter any problem.
