### ISSUE TITLE
Resize behaviour

### ISSUE THREAD

**Issue by mb925** [BioComputingUP/feature-viewer-typescript#4]
not responsive when resizing to a smaller screen

**Comment by Lisanna** [comment]
Could you specify? Smaller than what?

**Comment by mb925** [comment]
any width smaller then the original. When the page is loaded it has a width, if resizing to a smaller width, the bars are deformed and sometimes later buttons disappers

**Comment by mb925** [comment]
I don't understand exactly what I've changed in my CSS, but the problem is solved now...
