### ISSUE TITLE
sidebar bottons not responsive

### ISSUE THREAD

**Issue by mb925** [BioComputingUP/feature-viewer-typescript#5]
buttons under the tag 'svg g' (tag area) are not responsive. I have to manually change the property 'tranform:translate' in the css otherwise I can't see all the buttons properly.

**Comment by Lisanna** [comment]
I believe this issue was solved through private discussion, correct me if I am wrong. 
Please check all types of sidebar objects available. If you intend to use your own html, please do not set the `type` property on the sidebar object and fill the `content` property with your html code.
